[logger]
level = "INFO"
format = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

[file_handler]
enabled = true
file_path = "checkconnect.log"

[limited_file_handler]
enabled = true
file_path = "limited_checkconnect.log"
max_bytes = 1024
backup_count = 5

# [translations]
# language  = "en"

[gui]
enabled = true

[reports]
directory = "reports"

[network]
timeout = 10

[files]
ntp_servers = "ntp_servers.csv"
urls = "urls.csv"
