---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(3rd-party|COPYING|LICENSE|\.gitmodules|.*\.(ui|qrc|ts)$|LICENSES/|dist/|pnpm-lock.yaml)
ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: mkdocs.yml
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-json
        exclude: (\.devcontainer/devcontainer.json|\.vscode/)
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements
      - id: check-builtin-literals

  # Check and update pre-commit
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps

  # Code Style & Formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--safe]

  # Comprehensive Linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  # GitHub json checks
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.0
    hooks:
      - id: check-dependabot
      # - id: check-github-actions
      - id: check-github-workflows
      # - id: check-gitlab-ci
      - id: check-readthedocs
        # - id: check-taskfile
        args: [--verbose]

  # GitHub Workflows check
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  # Markdown specific
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.json"]

  # Links checker
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.6
    hooks:
      - id: markdown-link-check
        args: ["--config", ".markdown-link-check.json"]

  # Spell checker
  - repo: https://github.com/amperser/proselint
    rev: 0.14.0 # Use the latest stable version
    hooks:
      - id: proselint
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/streetsidesoftware/cspell
    rev: v8.4.0
    hooks:
      - id: cspell
        args: ["--config", "cspell.json", "**/*.md"]  # Only check Markdown files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0
    hooks:
      - id: prettier
        types: [markdown, javascript, css, json] # Specify file types to format

  # Typos and common mistakes
  - repo: https://github.com/crate-ci/typos
    rev: dictgen-v0.3.1
    hooks:
      - id: typos
        args: ["--config", "pyproject.toml"]
