[logger]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[file_handler]
enabled = true
file_path = "checkconnect.log"

[limited_file_handler]
enabled = true
file_path = "limited_checkconnect.log"
max_bytes = 1024
backup_count = 5

[gui]
enabled = true

[reports]
directory = "reports"

[network]
timeout = 5
ntp_servers = [
    "pool.ntp.org",
]
urls = [
    "https://example.com",
]
