name: "Setup Qt Dependencies"
description: "Installs Qt dependencies on Linux."
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Attempt to update, but don't fail if it doesn't work perfectly
        sudo apt-get update -y -q || true

        # List of dependencies
        DEPENDENCIES="libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xkb1 libxkbcommon-x11-0 libegl1"

        # Install each dependency, ignoring errors if they're already installed or can't be found
        for DEP in $DEPENDENCIES; do
          echo "Attempting to install: $DEP"
          sudo apt-get install -y --no-install-recommends "$DEP" || true
        done

        # Verify installation (optional, but good for debugging)
        echo "Verifying installation:"
        for DEP in $DEPENDENCIES; do
          dpkg -s "$DEP" > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "$DEP: Installed"
          else
            echo "::warning::$DEP: NOT installed"
          fi
        done
