name: "Setup Qt Dependencies"
description: "Installs Qt dependencies on Linux."
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get update
        DEPENDENCIES="libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xkb1 libxkbcommon-x11-0 libegl1"
        for DEP in $DEPENDENCIES; do
          dpkg -s "$DEP" > /dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "Installing $DEP"
            sudo apt-get install -y "$DEP"
            if [ $? -ne 0 ]; then
              echo "::error::Failed to install $DEP"
              exit 1
            fi
          fi
        done
