name: Commit Linting

on:
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR events

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: khulnasoft-lab/action-commit-lint@v2
