---
# SPDX-FileCopyrightText: (c) Wagner Santos
#
# SPDX-License-Identifier: MIT
#

name: Lint Commit Messages

on: [pull_request] # yamllint disable-line rule:truthy

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  commitlint:
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest

    steps:
      - name: "🧰 Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Check the commits"
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
