---
# SPDX-FileCopyrightText: Jef LeCompte
#
# SPDX-License-Identifier: MIT
#
name: 'Pull Request Linter'

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-pull-request-title:
    name: 'Lint pull request title'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: '🧰 Checkout Source Code'
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: 'Lint pull request title'
        uses: matthiashermsen/lint-pull-request-title@49458c35f9eeaaad64abfb7b1def719350b6a755 # v1.0.0
        with:
          allowed-pull-request-types: chore,feat,fix
