---
# SPDX-FileCopyrightText: Open Source Security Foundation (OpenSSF)
# SPDX-License-Identifier: Apache-2.0

name: Supply Chain Security Analysis

on: # yamlint disable-line rule:truthy
  schedule:
    - cron: 0 4 * * 1 # Run at 04:00 UTC every Monday

  push:
    branches:
      - main
      - develop
      - release/**
    paths-ignore:
      - '**.md'
      - '**.txt'
      - docs/**
      - .github/*.md
      - LICENSES/**
      - LICENSE
      - '.gitignore'

  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths-ignore:
      - '**.md'
      - '**.txt'
      - docs/**
      - .github/*.md
      - LICENSES/**
      - LICENSE
      - '.gitignore'

  workflow_dispatch:

permissions:
  contents: read # Base permissions for all jobs

concurrency:
  group: supply-chain-${{ github.ref }}
  cancel-in-progress: true # Ensures only one run per branch is active

jobs:
  analyze:
    name: Supply Chain Security Analysis
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      security-events: write # Required for SARIF uploads
      id-token: write # Needed to publish results with Scorecard

    steps:
      - name: 🔒 Harden Runner
        uses: step-security/harden-runner@v2.11.0
        with:
          egress-policy: audit

      - name: 🧰 Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🔍 Run Scorecard Analysis
        id: scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
